### ISSUE TITLE
The install method ignores a set proxy

### ISSUE THREAD

**Issue by eku** [Googlers-Repo/mmrl_install_tools#10]
A proxy configured in the WLAN profile is ignored by the install method, which leads to failure.

**Comment by LittleDipshit** [comment]
With the latest version you can set your own proxy inside MMRLINI

**Comment by eku** [comment]
> With the latest version you can set your own proxy inside MMRLINI

This may be a technical solution that in practice creates unnecessary effort when changing WLAN profiles. MMRL could query the system settings and pass them on to curl.

**Comment by DerGoogler** [comment]
Passing arguments `-L --proxy "$(settings get global http_proxy)"` should solve the problem
