### ISSUE TITLE
Fails to install 

### ISSUE THREAD

**Issue by sawdoctor** [Googlers-Repo/mmrl_install_tools#3]
Downloaded the latest release (Thanks for releasing a Magisk zip). If I try to install it with magisk canary it just fails with "Installation failed" message

**Comment by RichardBeisser** [comment]
I can confirm.
When you download the zip within MMRL --> still unzip error 
When you use zip from github --> is not a valid magisk-module

**Comment by kartikbillimoria** [comment]
Still unable to install module.zip downloaded from here

**Comment by RichardBeisser** [comment]
By the way, because it's the same message, the addon "Wi-Fi Bonding NoLog  [Qcom]" has the same problem.
It is not the correct zip.
With zip from github, installation works.

**Comment by DerGoogler** [comment]
Sorry guys for the late reply, had a hard week. I'll look into it!

**Comment by DerGoogler** [comment]
Could you try **v1.3.1**?

**Comment by sawdoctor** [comment]
Same here just get "installation failed" Running latest magisk canary

**Comment by DerGoogler** [comment]
It would be great to see logs. I can reproduce this but cant find the bug.

> It works on KernelSU

**Comment by sawdoctor** [comment]
- Copying zip to temp directory
- Installing module.zip
/data/user/0/hugjlvavpqg.ijf.fdx/cache/flash/update-binary: line 2: 
: not found
/data/user/0/hugjlvavpqg.ijf.fdx/cache/flash/update-binary: line 6: 
: not found
/data/user/0/hugjlvavpqg.ijf.fdx/cache/flash/update-binary: umask: line 7: illegal mode: 022
/data/user/0/hugjlvavpqg.ijf.fdx/cache/flash/update-binary: line 8: 
: not found
/data/user/0/hugjlvavpqg.ijf.fdx/cache/flash/update-binary: line 33: syntax error: unexpected end of file (expecting "}")
! Installation failed

**Comment by DerGoogler** [comment]
> * Copying zip to temp directory
> * Installing module.zip
>   /data/user/0/hugjlvavpqg.ijf.fdx/cache/flash/update-binary: line 2:
>   : not found
>   /data/user/0/hugjlvavpqg.ijf.fdx/cache/flash/update-binary: line 6:
>   : not found
>   /data/user/0/hugjlvavpqg.ijf.fdx/cache/flash/update-binary: umask: line 7: illegal mode: 022
>   /data/user/0/hugjlvavpqg.ijf.fdx/cache/flash/update-binary: line 8:
>   : not found
>   /data/user/0/hugjlvavpqg.ijf.fdx/cache/flash/update-binary: line 33: syntax error: unexpected end of file (expecting "}")
>   ! Installation failed

Thanks! Found the bug. Wrong file enconding.

**Comment by sawdoctor** [comment]
Thanks for all your hard work and sorry i should have known better and uploaded the log in the 1st place

**Comment by DerGoogler** [comment]
Does it now work? Need a confirmation to close.

**Comment by sawdoctor** [comment]
Yes installs fine now thanks 👍👍👍

**Comment by sawdoctor** [comment]
Only a cosmetic issue. Installing modules through the app now works fine but the toggle "enable install" doesn't work. Like I said it's only cosmetic but you can't toggle it on or off install just works

**Comment by DerGoogler** [comment]
This toggle is going to be removed in the next versions. The text below tells what you need.
