### ISSUE TITLE
mmrl-install-tools v1.4.3 not installable

### ISSUE THREAD

**Issue by RichardBeisser** [Googlers-Repo/mmrl_install_tools#5]
tried to install with different tool:
Magisk Delta, AMM
--> unzip error, not a valid magisk module

**Comment by DerGoogler** [comment]
Please provide logs otherwise we can't fix that bug.

**Comment by RichardBeisser** [comment]
@DerGoogler

Sorry for late feedback.
I found the problem. I always downloaded mmrl-install-tools.zip from your repo, within mmrl.
This file is another one than that from here from github.
the zip from your repo cannot be installed with any kind of magisk-manager. 

so, the only one you have to do is to replace the zip in your repo with the zip you published here at github.
Thanks.
