### ISSUE TITLE
InstallError: /system/bin/unzip: not found

### ISSUE THREAD

**Issue by bitteL3BN** [Googlers-Repo/mmrl_install_tools#6]
unzip binary is located in /system/xbin/unzip on my phone

can't install any module with up to date mmrl + installtools atm

_/data/adb/modules/mmrl_install_tools/system/usr/share/mmrl/bin/mmrl_local_install_v2[100] : /system/bin/unzip: not found_

**Comment by DerGoogler** [comment]
@bitteL3BN,

MMRL provides a dynamic module config page.

> Please delete these properties
> ```shell
> resetprop --delete persist.mmrlini.unzip
> resetprop --delete persist.mmrlini.zip
> resetprop --delete persist.mmrlini.curl
> ```

Open MMRL Install Tolls settings:
![Screenshot_20231128-105245_MMRL](https://github.com/Googlers-Repo/mmrl_install_tools/assets/54764558/fb62a6f3-e7fe-4563-9b1f-577852724b81)

Change it to your unzip location:
![Screenshot_20231128-105854_MMRL](https://github.com/Googlers-Repo/mmrl_install_tools/assets/54764558/f62e798a-b186-4f0b-897e-16084adf4d81)

**Comment by bitteL3BN** [comment]
oh god oopsie, thanks I searched for this feature at the wrong place - my bad

**Comment by DerGoogler** [comment]
Can I ask which Android version you have? Phone manufacturer, phone model, etc?

**Comment by bitteL3BN** [comment]
I still get the same error after changing the path to the correct location. Seems its still looking for unzip bin at the default path. I thought settings might need a reboot to change but that didnt help either.

Samsung Galaxy S8 SM-G950F Android 9

**Comment by DerGoogler** [comment]
@bitteL3BN,

issue should be fixed now. It the config page used old scope to store the bin paths.

> https://github.com/Googlers-Repo/mmrl_install_tools/releases/tag/v1.4.5
