### ISSUE TITLE
Unable to find root manager

### ISSUE THREAD

**Issue by cr24-OS** [Googlers-Repo/mmrl_install_tools#7]
Still cannot install modules. 
MMRL doesn't let you change the path to the Magisk Install CLI ($MSUCLI) but I think its wrong.

```shell
su -c magisk --path
 ```
 equals
```shell
 /sbin
```

_$MSUCLI = /sbin/magisk_ 
would be correct or am I wrong?

{
    "device": {
        "sdk": "28",
        "brand": "samsung",
        "model": "SM-G950F"
    },
    "application": {
        "package_name": "com.dergoogler.mmrl",
        "version_name": "1.10.6",
        "version_code": 1106
    },
    "root": {
        "manager": "Unknown",
        "version_name": "26.4:MAGISKSU",
        "version_code": 26400
    }
}

Edit: don't know if this issue belongs to MMRL itself or to its installtools

**Comment by DerGoogler** [comment]
The other reason could be our detection system, the way we detect Magisk and KernelSU. 

We detect it over mounts and related file and folder paths

**Comment by DerGoogler** [comment]
Is magisk hidden or something?

**Comment by DerGoogler** [comment]
@cr24-OS, could you run this command? Need to check if magisk is in mounts

```shell
su -c cat /proc/self/mounts | grep magisk
```

**Comment by DerGoogler** [comment]
Could you try the debug build? https://github.com/DerGoogler/MMRL/actions/runs/7052293529
